import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {
  PHISKRIT_SCHEMA, PHISKRIT_MAX_BYTES,
  validatePhiSkritComposition, parsePhiSkritCompositionText,
} from "../src/lib/phiskritCompositionReview.ts";

/**
 * Golden fixture independently populated from documented PhiSkrit v0.5
 * output: LGL repeated twice, then GGLL once, at 120 BPM.
 * Event values are literals, not generated by the MBL implementation.
 */
const sample = {
  schema: "phiskrit.rhythm.composition.v1",
  source: "PhiSkrit",
  interpretation: "ORIGINAL_MODERN_LG_ARRANGEMENT_NOT_HISTORICAL",
  title: "Nested Rhythm No. 1",
  bpm: 120,
  ticksPerBeat: 480,
  clips: [{ pattern: "LGL", repeats: 2 }, { pattern: "GGLL", repeats: 1 }],
  eventCount: 10,
  totalTicks: 6720,
  events: [
    { clipIndex: 0, repetition: 0, position: 0, syllable: "L", startTick: 0, durationTicks: 480, midiNote: 67, velocity: 78 },
    { clipIndex: 0, repetition: 0, position: 1, syllable: "G", startTick: 480, durationTicks: 960, midiNote: 60, velocity: 108 },
    { clipIndex: 0, repetition: 0, position: 2, syllable: "L", startTick: 1440, durationTicks: 480, midiNote: 67, velocity: 78 },
    { clipIndex: 0, repetition: 1, position: 0, syllable: "L", startTick: 1920, durationTicks: 480, midiNote: 67, velocity: 78 },
    { clipIndex: 0, repetition: 1, position: 1, syllable: "G", startTick: 2400, durationTicks: 960, midiNote: 60, velocity: 108 },
    { clipIndex: 0, repetition: 1, position: 2, syllable: "L", startTick: 3360, durationTicks: 480, midiNote: 67, velocity: 78 },
    { clipIndex: 1, repetition: 0, position: 0, syllable: "G", startTick: 3840, durationTicks: 960, midiNote: 60, velocity: 108 },
    { clipIndex: 1, repetition: 0, position: 1, syllable: "G", startTick: 4800, durationTicks: 960, midiNote: 60, velocity: 108 },
    { clipIndex: 1, repetition: 0, position: 2, syllable: "L", startTick: 5760, durationTicks: 480, midiNote: 67, velocity: 78 },
    { clipIndex: 1, repetition: 0, position: 3, syllable: "L", startTick: 6240, durationTicks: 480, midiNote: 67, velocity: 78 },
  ],
};

const clone = value => structuredClone(value);

test("independent receiver accepts the documented PhiSkrit v0.5 golden composition", () => {
  const review = validatePhiSkritComposition(sample);
  assert.equal(review.verdict, "VALID_FOR_VISUAL_REVIEW");
  assert.equal(review.composition.schema, PHISKRIT_SCHEMA);
  assert.equal(review.composition.totalTicks, 6720);
  assert.equal(review.totalBeats, 14);
  assert.equal(review.durationSeconds, 7);
  assert.equal(review.lightCount, 6);
  assert.equal(review.heavyCount, 4);
  assert.deepEqual(review.composition.events, sample.events);
  assert.match(review.warning, /not grant audio/i);
});

test("reordered object keys still work; unknown event and metadata keys fail", () => {
  const differentlyOrdered = { title: sample.title, ...sample };
  differentlyOrdered.events = differentlyOrdered.events.map(e => ({
    velocity: e.velocity, midiNote: e.midiNote, ...e,
  }));
  assert.equal(validatePhiSkritComposition(differentlyOrdered).composition.title, sample.title);
  assert.throws(() => validatePhiSkritComposition({ ...sample, remoteAudioUrl: "https://example.com" }), /did not match/);
  const altered = clone(sample);
  altered.events[0].remoteScript = "javascript:alert(1)";
  assert.throws(() => validatePhiSkritComposition(altered), /did not match/);
});

test("reject modified ticks, metadata, schema, tempo, and invented catalog identities", () => {
  const badTick = clone(sample);
  badTick.events[6].startTick = 4801;
  assert.throws(() => validatePhiSkritComposition(badTick), /did not match/);
  assert.throws(() => validatePhiSkritComposition({ ...sample, interpretation: "VERIFIED_ANCIENT_PROOF" }), /did not match/);
  assert.throws(() => validatePhiSkritComposition({ ...sample, source: "someone-else" }), /did not match/);
  assert.throws(() => validatePhiSkritComposition({ ...sample, schema: "mbl-mix-v1" }), /Only phiskrit/);
  assert.throws(() => validatePhiSkritComposition({ ...sample, bpm: 199 }), /did not match/);
  assert.throws(() => validatePhiSkritComposition({ ...sample, albumId: "fake" }), /did not match/);
});

test("reject invalid clips, repeats, excessive events and unsafe titles", () => {
  assert.throws(() => validatePhiSkritComposition({ ...sample, clips: [] }), /1–8 clips/);
  assert.throws(() => validatePhiSkritComposition({ ...sample, clips: Array(9).fill(sample.clips[0]) }), /1–8 clips/);
  assert.throws(() => validatePhiSkritComposition({ ...sample, clips: [{ pattern: "lgl", repeats: 1 }] }), /uppercase/);
  assert.throws(() => validatePhiSkritComposition({ ...sample, clips: [{ pattern: "LG", repeats: 5 }] }), /repeat/);
  assert.throws(() => validatePhiSkritComposition({ ...sample, title: "bad\nline" }), /printable/);
  assert.throws(() => validatePhiSkritComposition({
    ...sample, clips: Array.from({ length: 5 }, () => ({ pattern: "GGGGGGGG", repeats: 4 }))
  }), /128-event/);
  const tooBig = " ".repeat(PHISKRIT_MAX_BYTES + 1);
  assert.throws(() => parsePhiSkritCompositionText(tooBig), /96 KiB/);
  assert.throws(() => parsePhiSkritCompositionText("{ invalid"), /valid JSON/);
  assert.throws(() => parsePhiSkritCompositionText(JSON.stringify({ format: "mbl-mix-v1", tracks: [] })), /Only phiskrit/);
});

test("receiver is a separate passive interface, no audio permissions or mix bridge", () => {
  const code = readFileSync("src/components/PhiSkritReview.tsx", "utf8");
  const desk = readFileSync("src/components/FieldDesk.tsx", "utf8");
  const checker = readFileSync("src/lib/phiskritCompositionReview.ts", "utf8");
  assert.match(desk, /<PhiSkritReview \/>/);
  assert.match(desk, /PhiSkrit Review/);
  assert.match(code, /parsePhiSkritCompositionText/);
  assert.match(code, /Read only/);
  assert.doesNotMatch(code + checker, /useHouse|onPlay\(|queueMix\(|AudioContext|new Audio\(|\.play\(|eval\(|fetch\(|postMessage\(/);
  assert.match(checker, /every.*equalShape|equalShape/);
});
